[pytest] #everything below is configuration for pytest

#current Project Directory
pythonpath = .

#look only inside the tests folder which is in the root of the project
testpaths = tests

#only files starting with test_ are test files
python_files = test_*.py

#Inside a test file, pytest only runs functions whose names start with test_
python_functions = test_*

#to run and to create report and trace any failure
addopts =
    -v
    --tb=short
    --alluredir=allure-results

#to group tests and run them based on the markers defined below
markers =
    scoring: Bowling scoring tests
    validation: Bowling validation tests